### ISSUE TITLE
py什么版本的呀  运行一直报 语法不对

### ISSUE THREAD

**Issue by lixiaokun777** [Chanpoe/wechat-morning-weather#1]
<img width="477" alt="1661743333152" src="https://user-images.githubusercontent.com/57617854/187116634-16517c37-046e-468b-808b-67d2f7bcb4db.png">

**Comment by Chanpoe** [comment]
python3.10版本的，你查看一下，如果还有问题可以加我的QQ 941407617&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月29日(周一) 中午11:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Chanpoe/wechat-morning-weather] py什么版本的呀  运行一直报 语法不对 (Issue #1)

**Comment by lixiaokun777** [comment]
> python3.10版本的，你看一下，如果还有问题可以加我的QQ 941407617 
> […](#)
> ---原始邮件---发件人：***@***.***> 时间：2222 年（周一）11:28 月 2 日上午 209 日：***@******gt; 抄送：***@***.***>; 主题：[Chanpoe/wechat-morning-weather] py什么版本的呀运行一直报语法错误（问题#1）

确实是版本不行 我的py版本3.9 我跑了一docker可以了。
